services:
  auth-app:
    build:
      context: ./Services
      dockerfile: ./apps/auth/Dockerfile
    container_name: service-auth-app
    ports:
      - "4002:4002"
    env_file:
      - ./Services/.env
    networks:
      - networkapp

  gateway-app:
    build:
      context: ./Services
      dockerfile: ./apps/gateway/Dockerfile
    container_name: service-gateway-app
    ports:
      - "4000:4000"
    env_file:
      - ./Services/.env
    networks:
      - networkapp

  user-app:
    build:
      context: ./Services
      dockerfile: ./apps/user/Dockerfile
    container_name: service-user-app
    ports:
      - "4001:4001"
    env_file:
      - ./Services/.env
    networks:
      - networkapp

  password-app:
    build:
      context: ./Services
      dockerfile: ./apps/password/Dockerfile
    container_name: service-password-app
    ports:
      - "4003:4003"
    env_file:
      - ./Services/.env
    networks:
      - networkapp

networks:
  networkapp:
    driver: bridge
